"""
astrocolibri/consumer.py

Astro-Colibri alert Consumer.

Inspired by gcn-kafka (https://github.com/nasa-gcn/gcn-kafka-python). This
class exposes ONLY message consumption. Publishing is restricted to the
internal Astro-Colibri broker application and is intentionally absent from
this package — there is no Producer here, and there never will be.
"""

from __future__ import annotations

import uuid
from typing import Any, Dict, Generator, List, Optional

from confluent_kafka import Consumer as _ConfluentConsumer
from confluent_kafka import KafkaError, KafkaException, Message

from .exceptions import (
    AstrocolibriAuthError,
    AstrocolibriConfigError,
    AstrocolibriKafkaError,
)

# Topics available on the official broker
TOPICS = [
    "astrocolibri.all.JSON",
    "astrocolibri.all.VOEvent",
    "astrocolibri.important.JSON",
    "astrocolibri.important.VOEvent",
    "astrocolibri.heartbeat",
]


class Consumer:
    """
    Astro-Colibri alert consumer.

    Subscribes to Astro-Colibri broker topics and receives alerts in real
    time, authenticated via SASL/SCRAM-SHA-512.

    .. note::
        This library does **not** allow publishing alerts. Publishing is
        restricted to the Astro-Colibri infrastructure itself.

    Quick start::

        from astrocolibri import Consumer

        with Consumer(
            username="your-username",
            password="your-password",
        ) as consumer:
            consumer.subscribe(["astrocolibri.all.JSON"])

            for message in consumer.consume(timeout=30):
                print(message.value())

    Infinite loop (blocking)::

        for message in consumer.consume():   # timeout=-1 by default
            handle(message.value())

    With a timeout (non-blocking)::

        while True:
            for message in consumer.consume(timeout=5.0):
                handle(message.value())
            do_other_work()
    """

    #: Astro-Colibri official broker address.
    DEFAULT_BROKER_URL: str = "broker.astro-colibri.science:9092"

    def __init__(
        self,
        username: str,
        password: str,
        *,
        broker_url: Optional[str] = None,
        group_id: Optional[str] = None,
        start_at: str = "earliest",
        security_protocol: str = "SASL_SSL",
        config: Optional[Dict[str, Any]] = None,
    ) -> None:
        """
        Initialize the Astro-Colibri Consumer.

        Args:
            username:
                Username generated by the Astro-Colibri account GUI.
            password:
                Password generated alongside ``username``.
            broker_url:
                Kafka broker address. Defaults to the official Astro-Colibri
                broker (``broker.astro-colibri.science:9092``). For local testing
                against your own broker: ``"localhost:9092"``.
            group_id:
                Kafka consumer group ID.

                - If provided, Kafka remembers your read position (offset)
                  across sessions: you resume exactly where you left off.
                - If omitted (default), a random UUID is generated on every
                  startup: you re-read from ``start_at`` every time, with
                  no progress persisted.
            start_at:
                Starting position for a **new** ``group_id``.

                - ``"earliest"`` (default): receive every alert available
                  within the retention window.
                - ``"latest"``: receive only new alerts published after
                  connecting.
            security_protocol:
                Kafka security protocol.

                - ``"SASL_SSL"`` (default): SASL with TLS encryption for the
                  official public broker.
                - ``"SASL_PLAINTEXT"``: intended only for a trusted local
                  development broker.
            config:
                Extra confluent-kafka options. Authentication and consumer
                group identity remain managed by this client.

        Raises:
            AstrocolibriConfigError: If ``start_at`` is invalid.
            AstrocolibriAuthError: If the connection to the broker fails
                (invalid credentials, network issue, etc.).

        Example::

            # Local broker for testing
            consumer = Consumer(
                username="alice",
                password="alice-strong-password",
                broker_url="localhost:9092",
            )

            # Official broker (default)
            consumer = Consumer(
                username="alice",
                password="alice-strong-password",
            )
        """
        if start_at not in ("earliest", "latest"):
            raise AstrocolibriConfigError(
                f"start_at must be 'earliest' or 'latest', got: '{start_at}'."
            )

        # Kafka ACLs isolate each account under a username-derived group
        # prefix. No group_id still means no offset persistence because the
        # random suffix changes on every startup.
        self._persistent = group_id is not None
        group_prefix = f"{username}."
        group_suffix = group_id or str(uuid.uuid4())
        resolved_group_id = (
            group_suffix
            if group_suffix.startswith(group_prefix)
            else f"{group_prefix}{group_suffix}"
        )

        base_config: Dict[str, Any] = {
            "bootstrap.servers": broker_url or self.DEFAULT_BROKER_URL,
            "security.protocol": security_protocol,
            "sasl.mechanism": "SCRAM-SHA-512",
            "sasl.username": username,
            "sasl.password": password,
            "group.id": resolved_group_id,
            "auto.offset.reset": start_at,
            "enable.auto.commit": self._persistent,
            "auto.commit.interval.ms": 5000,
            "session.timeout.ms": 30_000,
            "heartbeat.interval.ms": 10_000,
            "max.poll.interval.ms": 300_000,
            "reconnect.backoff.ms": 500,
            "reconnect.backoff.max.ms": 10_000,
        }

        if config:
            base_config.update(config)
            base_config.update(
                {
                    "sasl.mechanism": "SCRAM-SHA-512",
                    "sasl.username": username,
                    "sasl.password": password,
                    "group.id": resolved_group_id,
                }
            )

        try:
            self._consumer = _ConfluentConsumer(base_config)
        except KafkaException as exc:
            raise AstrocolibriAuthError(
                f"Could not connect to the Astro-Colibri broker "
                f"({base_config['bootstrap.servers']}): {exc}"
            ) from exc

    # ── Subscription ─────────────────────────────────────────────────────────

    def subscribe(
        self,
        topics: List[str],
        *,
        on_assign: Optional[Any] = None,
        on_revoke: Optional[Any] = None,
        on_lost: Optional[Any] = None,
    ) -> None:
        """
        Subscribe to a list of Astro-Colibri topics.

        Args:
            topics: Topic names to subscribe to. Example:

                .. code-block:: python

                    consumer.subscribe([
                        "astrocolibri.all.JSON",
                        "astrocolibri.all.VOEvent",
                    ])

            on_assign: Callback ``(consumer, partitions)`` called when
                partitions are assigned to this consumer.
            on_revoke: Callback ``(consumer, partitions)`` called when
                partitions are revoked from it.
            on_lost: Callback ``(consumer, partitions)`` called when
                partitions are lost involuntarily.
        """
        kwargs: Dict[str, Any] = {}
        if on_assign:
            kwargs["on_assign"] = on_assign
        if on_revoke:
            kwargs["on_revoke"] = on_revoke
        if on_lost:
            kwargs["on_lost"] = on_lost

        self._consumer.subscribe(topics, **kwargs)

    # ── Consuming ────────────────────────────────────────────────────────────

    def consume(
        self,
        num_messages: int = 1,
        timeout: float = -1,
    ) -> Generator[Message, None, None]:
        """
        Consume messages from the subscribed topics.

        Yields messages one at a time. ``_PARTITION_EOF`` errors (end of
        partition) are silently ignored; any other Kafka error raises
        :exc:`AstrocolibriKafkaError`.

        Args:
            num_messages:
                Maximum number of messages fetched per internal batch.
                Does not affect the stream itself: the generator always
                yields one message at a time.
            timeout:
                - ``-1`` (default): blocks indefinitely until the next
                  message arrives. The generator never terminates on its own.
                - ``> 0``: returns after ``timeout`` seconds with no
                  message. The generator terminates — useful for periodic
                  processing between batches.

        Yields:
            :class:`confluent_kafka.Message`

            Useful methods:

            - ``message.value()`` → ``bytes`` — alert payload
            - ``message.key()``   → ``bytes | None`` — message key
            - ``message.topic()`` → ``str``
            - ``message.partition()`` → ``int``
            - ``message.offset()``    → ``int``
            - ``message.timestamp()`` → ``(type, timestamp_ms)``

        Raises:
            AstrocolibriKafkaError: On an unrecoverable Kafka error.

        Examples:

            Infinite loop (blocks until the next message)::

                for message in consumer.consume():
                    data = json.loads(message.value())
                    print(data)

            With a timeout (yields control between batches)::

                while True:
                    for message in consumer.consume(timeout=5.0):
                        handle(message)
                    check_app_state()
        """
        while True:
            msgs = self._consumer.consume(
                num_messages=num_messages,
                timeout=timeout,
            )
            if not msgs:
                # Timeout elapsed with no message → stop the generator
                return

            for msg in msgs:
                if msg.error():
                    code = msg.error().code()
                    if code == KafkaError._PARTITION_EOF:
                        # End of partition: expected, keep going
                        continue
                    raise AstrocolibriKafkaError(
                        f"Kafka error on {msg.topic()} "
                        f"[partition={msg.partition()}]: {msg.error()}"
                    )
                yield msg

    # ── Lifecycle ────────────────────────────────────────────────────────────

    def close(self) -> None:
        """
        Cleanly close the consumer and release resources.

        Commits any pending offsets (if ``group_id`` is persistent) and
        leaves the consumer group.
        """
        self._consumer.close()

    def __enter__(self) -> "Consumer":
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool:
        self.close()
        return False
