"""
astrocolibri/consumer.py

Astro-Colibri alert Consumer.

Inspired by gcn-kafka (https://github.com/nasa-gcn/gcn-kafka-python). This
class exposes ONLY message consumption. Publishing is restricted to the
internal Astro-Colibri broker application and is intentionally absent from
this package — there is no Producer here, and there never will be.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Generator, List, Optional, Union

from confluent_kafka import Consumer as _ConfluentConsumer
from confluent_kafka import KafkaError, KafkaException, Message

from .alert import Alert
from .exceptions import (
    AstrocolibriAuthError,
    AstrocolibriConfigError,
    AstrocolibriKafkaError,
)

logger = logging.getLogger(__name__)

# Topics available on the official broker
TOPICS = [
    "astrocolibri.all.JSON",
    "astrocolibri.all.VOEvent",
    "astrocolibri.important.JSON",
    "astrocolibri.important.VOEvent",
    "astrocolibri.heartbeat",
]

# Kafka conditions that a long-running consumer is expected to ride out:
# librdkafka reconnects and rejoins on its own, so they are logged and
# skipped instead of ending the stream.
_TRANSIENT_ERROR_CODES = {
    code
    for code in (
        KafkaError._PARTITION_EOF,
        KafkaError._TRANSPORT,
        KafkaError._ALL_BROKERS_DOWN,
        KafkaError._TIMED_OUT,
        getattr(KafkaError, "_MAX_POLL_EXCEEDED", None),
    )
    if code is not None
}


class Consumer:
    """
    Astro-Colibri alert consumer.

    Subscribes to Astro-Colibri broker topics and receives alerts in real
    time, authenticated via SASL/SCRAM-SHA-512.

    .. note::
        This library does **not** allow publishing alerts. Publishing is
        restricted to the Astro-Colibri infrastructure itself.

    Payloads arrive decoded: :meth:`Alert.value` returns a ``dict`` on the
    JSON topics and the XML document as ``str`` on the VOEvent topics, never
    raw bytes.

    Quick start — listen continuously::

        from astrocolibri import Consumer

        with Consumer(
            username="your-username",
            password="your-password",
        ) as consumer:
            consumer.subscribe(["astrocolibri.all.JSON"])

            # Runs forever, waiting for the next alert.
            for alert in consumer.consume():
                data = alert.value()
                print(data["id"], data["ra"], data["dec"])

    Batch mode — return control between bursts of alerts::

        while True:
            for alert in consumer.consume(timeout=5.0):
                handle(alert.value())
            do_other_work()
    """

    #: Astro-Colibri official broker address.
    DEFAULT_BROKER_URL: str = "broker.astro-colibri.science:9092"

    #: Group name used when no ``group_id`` is given, appended to the
    #: username prefix (e.g. ``"alice.default"``).
    DEFAULT_GROUP_SUFFIX: str = "default"

    def __init__(
        self,
        username: str,
        password: str,
        *,
        broker_url: Optional[str] = None,
        group_id: Optional[str] = None,
        start_at: str = "earliest",
        security_protocol: str = "SASL_SSL",
        decode: bool = True,
        poll_interval: float = 1.0,
        config: Optional[Dict[str, Any]] = None,
    ) -> None:
        """
        Initialize the Astro-Colibri Consumer.

        Args:
            username:
                Username generated by the Astro-Colibri account GUI.
            password:
                Password generated alongside ``username``.
            broker_url:
                Kafka broker address. Defaults to the official Astro-Colibri
                broker (``broker.astro-colibri.science:9092``). For local testing
                against your own broker: ``"localhost:9092"``.
            group_id:
                Kafka consumer group ID. Prefixed with your username to
                satisfy the per-user ACL, so ``"my-pipeline"`` becomes
                ``"alice.my-pipeline"``.

                - Omitted (default): the group ``"<username>.default"`` is
                  used. Kafka remembers your read position (offset) across
                  sessions, so you resume exactly where you left off.
                - Running several scripts on the same credentials: give each
                  one its own ``group_id``. Consumers sharing a group have the
                  partitions split between them, so each would otherwise
                  receive only part of the stream.
            start_at:
                Starting position for a **new** ``group_id``.

                - ``"earliest"`` (default): receive every alert available
                  within the retention window.
                - ``"latest"``: receive only new alerts published after
                  connecting.
            security_protocol:
                Kafka security protocol.

                - ``"SASL_SSL"`` (default): SASL with TLS encryption for the
                  official public broker.
                - ``"SASL_PLAINTEXT"``: intended only for a trusted local
                  development broker.
            decode:
                - ``True`` (default): :meth:`consume` yields
                  :class:`~astrocolibri.alert.Alert` objects whose
                  ``value()`` is the decoded payload — a ``dict`` on the
                  JSON topics, the XML document as ``str`` on the VOEvent
                  topics.
                - ``False``: yields the raw
                  :class:`confluent_kafka.Message`, whose ``value()`` is
                  ``bytes``. For code that decodes the payload itself.
            poll_interval:
                Seconds spent in each internal poll while :meth:`consume`
                waits for the next alert. It does not change what you
                receive; it only decides how quickly a blocking
                ``consume()`` notices Ctrl-C. Lower it for a snappier
                shutdown, raise it to poll the broker less often.
            config:
                Extra confluent-kafka options. Authentication and consumer
                group identity remain managed by this client.

        Raises:
            AstrocolibriConfigError: If ``start_at`` is invalid.
            AstrocolibriAuthError: If the connection to the broker fails
                (invalid credentials, network issue, etc.).

        Example::

            # Local broker for testing
            consumer = Consumer(
                username="alice",
                password="alice-strong-password",
                broker_url="localhost:9092",
            )

            # Official broker (default)
            consumer = Consumer(
                username="alice",
                password="alice-strong-password",
            )
        """
        if start_at not in ("earliest", "latest"):
            raise AstrocolibriConfigError(
                f"start_at must be 'earliest' or 'latest', got: '{start_at}'."
            )

        if poll_interval <= 0:
            raise AstrocolibriConfigError(
                f"poll_interval must be > 0 seconds, got: {poll_interval}."
            )

        self._decode = decode
        self._poll_interval = poll_interval

        group_prefix = f"{username}."
        if group_id is None:
            resolved_group_id = f"{group_prefix}{self.DEFAULT_GROUP_SUFFIX}"
        else:
            resolved_group_id = (
                group_id
                if group_id.startswith(group_prefix)
                else f"{group_prefix}{group_id}"
            )

        base_config: Dict[str, Any] = {
            "bootstrap.servers": broker_url or self.DEFAULT_BROKER_URL,
            "security.protocol": security_protocol,
            "sasl.mechanism": "SCRAM-SHA-512",
            "sasl.username": username,
            "sasl.password": password,
            "group.id": resolved_group_id,
            "auto.offset.reset": start_at,
            "enable.auto.commit": True,
            "auto.commit.interval.ms": 5000,
            "session.timeout.ms": 30_000,
            "heartbeat.interval.ms": 10_000,
            "max.poll.interval.ms": 300_000,
            "reconnect.backoff.ms": 500,
            "reconnect.backoff.max.ms": 10_000,
        }

        if config:
            base_config.update(config)
            base_config.update(
                {
                    "sasl.mechanism": "SCRAM-SHA-512",
                    "sasl.username": username,
                    "sasl.password": password,
                    "group.id": resolved_group_id,
                }
            )

        try:
            self._consumer = _ConfluentConsumer(base_config)
        except KafkaException as exc:
            raise AstrocolibriAuthError(
                f"Could not connect to the Astro-Colibri broker "
                f"({base_config['bootstrap.servers']}): {exc}"
            ) from exc

    # ── Subscription ─────────────────────────────────────────────────────────

    def subscribe(
        self,
        topics: List[str],
        *,
        on_assign: Optional[Any] = None,
        on_revoke: Optional[Any] = None,
        on_lost: Optional[Any] = None,
    ) -> None:
        """
        Subscribe to a list of Astro-Colibri topics.

        Args:
            topics: Topic names to subscribe to. Example:

                .. code-block:: python

                    consumer.subscribe([
                        "astrocolibri.all.JSON",
                        "astrocolibri.all.VOEvent",
                    ])

            on_assign: Callback ``(consumer, partitions)`` called when
                partitions are assigned to this consumer.
            on_revoke: Callback ``(consumer, partitions)`` called when
                partitions are revoked from it.
            on_lost: Callback ``(consumer, partitions)`` called when
                partitions are lost involuntarily.
        """
        kwargs: Dict[str, Any] = {}
        if on_assign:
            kwargs["on_assign"] = on_assign
        if on_revoke:
            kwargs["on_revoke"] = on_revoke
        if on_lost:
            kwargs["on_lost"] = on_lost

        self._consumer.subscribe(topics, **kwargs)

    # ── Consuming ────────────────────────────────────────────────────────────

    def consume(
        self,
        num_messages: int = 1,
        timeout: float = -1,
    ) -> Generator[Union[Alert, Message], None, None]:
        """
        Consume alerts from the subscribed topics, one at a time.

        By default this never ends: it keeps waiting for the next alert, so
        a single ``for`` loop is a complete listener. Transient Kafka
        conditions (end of partition, a broker connection dropping, the
        group rebalancing) are logged and skipped rather than ending the
        stream; only an unrecoverable error raises.

        Args:
            num_messages:
                Maximum number of messages fetched per internal batch.
                Does not affect the stream itself: the generator always
                yields one alert at a time.
            timeout:
                - ``-1`` (default): listen forever. The generator never
                  terminates on its own, and internally polls the broker in
                  ``poll_interval`` slices so Ctrl-C stays responsive.
                - ``> 0``: stop after ``timeout`` seconds without a new
                  alert. Use this when your program has other work to do
                  between bursts — wrap it in ``while True:``.

        Yields:
            :class:`~astrocolibri.alert.Alert` — payload already decoded:

            - ``alert.value()``  → ``dict`` on a JSON topic, XML ``str`` on
              a VOEvent topic
            - ``alert.text()``   → ``str`` — payload as published
            - ``alert.json()``   → parsed JSON, whatever the topic
            - ``alert.key()``    → ``str | None`` — the event id
            - ``alert.headers()``→ ``dict[str, str]`` — broker metadata
            - ``alert.format``   → ``"json"`` | ``"voevent"``
            - ``alert.raw``      → ``bytes`` — undecoded payload
            - ``alert.topic()`` / ``.partition()`` / ``.offset()`` /
              ``.timestamp()``

            With ``decode=False`` on the Consumer, the raw
            :class:`confluent_kafka.Message` is yielded instead and
            ``value()`` is ``bytes``.

        Raises:
            AstrocolibriKafkaError: On an unrecoverable Kafka error.

        Examples:

            Listen continuously — the normal case::

                for alert in consumer.consume():
                    data = alert.value()
                    print(data["id"], data["type"])

            Batch mode, to do other work between alerts::

                while True:
                    for alert in consumer.consume(timeout=5.0):
                        handle(alert.value())
                    check_app_state()
        """
        listen_forever = timeout is None or timeout < 0
        poll_timeout = self._poll_interval if listen_forever else timeout

        while True:
            msgs = self._consumer.consume(
                num_messages=num_messages,
                timeout=poll_timeout,
            )
            if not msgs:
                if listen_forever:
                    # Nothing this slice; keep waiting for the next alert.
                    continue
                # Timeout elapsed with no message → stop the generator
                return

            for msg in msgs:
                if msg.error():
                    if self._is_transient(msg):
                        continue
                    raise AstrocolibriKafkaError(
                        f"Kafka error on {msg.topic()} "
                        f"[partition={msg.partition()}]: {msg.error()}"
                    )
                yield Alert(msg) if self._decode else msg

    @staticmethod
    def _is_transient(msg: Message) -> bool:
        """Whether the error on `msg` is one the client recovers from itself."""
        error = msg.error()
        code = error.code()

        if code == KafkaError._PARTITION_EOF:
            # End of partition: expected on an idle topic, not worth a log line.
            return True

        retriable = False
        if code in _TRANSIENT_ERROR_CODES:
            retriable = True
        else:
            # librdkafka classifies the error itself; trust it when it does.
            try:
                retriable = bool(error.retriable())
            except (AttributeError, TypeError):  # pragma: no cover - old clients
                retriable = False

        if retriable:
            logger.warning(
                "Transient Kafka condition on %s [partition=%s]: %s — "
                "the client recovers on its own, continuing to listen",
                msg.topic(),
                msg.partition(),
                error,
            )
        return retriable

    # ── Lifecycle ────────────────────────────────────────────────────────────

    def close(self) -> None:
        """
        Cleanly close the consumer and release resources.

        Commits any pending offsets and leaves the consumer group, so the
        next run of this ``group_id`` resumes from here.
        """
        self._consumer.close()

    def __enter__(self) -> "Consumer":
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool:
        self.close()
        return False
